### ISSUE TITLE
增加合并文件夹的功能

### ISSUE THREAD

**Issue by marquistj13** [CNchence/Wallpaper_Reptile#1]
1. 建议增加一项询问是否合并文件夹的功能
即想将所有图片放在一个文件夹，当然原来分文件夹的形式也可以保留，你询问我是否需要新建文件夹就行了嘛
1.  分辨率的选择，建议用Dictionary表示分辨率，这样我就可以用数字选择分辨率了
1.  增加膜🐸 的功能

**Comment by CNchence** [comment]
感谢马奎斯
